### ISSUE TITLE
transparent proxy for http and https

### ISSUE THREAD

**Issue by SeameX** [qwj/python-proxy#21]
Hi,
I want a transparent proxy for http and https. At the moment i think there is a feature missing.

Setup:
Linux Laptop
2 Networks
- Home network direct internet access
- Corporate network internet access only through proxy

So i want that pproxy uses a proxy if proxy is alive otherwise fall back to direct connections.

Redirect all my local traffic to pproxy via iptables:
iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner proxy --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner proxy --dport 443 -j REDIRECT --to-port 8080

pproxy -l redir://:8080/ -r http://142.93.135.90:8080 -a 3 -vv

Start as user and group "proxy" (so that direct connections will work)
Redirect traffic to upstream proxy (corporate)
Try if alive in a 3 second interval
Verbose to check whats going on

Problem:
Tests:
```
curl -I http://seamex.de
curl: (8) Weird server reply
curl -I https://seamex.de
HTTP/2 200 ...
```

Looks like just the https traffic is redirected. Can you please fix that :)
https and http traffic needs to be redirected to the upstream proxy  (i also tried auto detection like: redir+http but that dont work)

Workaround:
I installed redsocks that listens on two ports one for http and one for https to do the different connect methods (http-relay, http-connect). Redsocks upstreams to pproxy (as http started). But i dont want to use two proxies when one can handel that ;)

**Comment by SeameX** [comment]
Hi,
the upsteam proxy i posted above is a public one for testing purposes so you can test yourself. 

```
pproxy -r http://142.93.135.90:8080 --test http://google.com
Traceback (most recent call last):
  File "/usr/local/bin/pproxy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pproxy/server.py", line 441, in main
    asyncio.run(test_url(args.test, args.rserver))
AttributeError: module 'asyncio' has no attribute 'run'
```

When i start like: 
`pproxy -l http://:8080/ -r http://142.93.135.90:8080 -vv`
and configuring a proxy in e.g. firefox pointing to localhost:8080 both http and https is working.

That what i want is that the proxy is doing http-relay for http requests and http-connect on https requests in redir mode. At the moment it is just doing connect thats why http requests are not working.

**Comment by qwj** [comment]
Sorry that the --test only works with Python 3.7
I have tested the public http proxy. It doesn’t accept CONNECT method for
http :80 traffic, only accepts GET/POST.
pproxy doesn’t have the ability to act as a GET/POST proxy client now.


SeameX <notifications@github.com>

**Comment by SeameX** [comment]
Sorry for the delay. For me this is a feature request then :)
